obj-$(CONFIG_AW_AXP) += axp-core.o
obj-$(CONFIG_AW_AXP) += axp-sysfs.o
obj-$(CONFIG_AW_AXP) += axp-virtual.o
obj-$(CONFIG_AW_AXP) += axp-powerkey.o
obj-$(CONFIG_AW_AXP) += axp-charger.o
obj-$(CONFIG_AW_AXP) += axp-gpio.o
obj-$(CONFIG_AW_AXP) += axp-regulator.o
obj-$(CONFIG_AW_AXP) += nmi/sunxi-nmi.o

#AXP22X
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-regulator.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-charger.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-gpio.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-powerkey.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-virtual.o

#AXP80X
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-regulator.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-gpio.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-powerkey.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-virtual.o
