#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MSG2XXX) := s23501t0-g.o

s23501t0-g-objs	:= ilitek_drv_main.o ilitek_drv_mtk.o ilitek_drv_update.o ilitek_drv_iliproc.o
