#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GT5688) += gt5688.o
gt5688-objs := gt1x.o gt1x_generic.o gt1x_tools.o gt1x_update.o

