# SUNXI Platform Support
snd-soc-sunxi-objs := sunxi-pcm.o
snd-soc-sunxi-hdmi-objs := sunxi-hdmi.o
snd-soc-sunxi-daudio-objs := sunxi-daudio.o
snd-soc-sunxi-spdif-objs := sunxi-spdif.o spdif-utils.o
snd-soc-sunxi-cpudai-objs := sunxi-cpudai.o
snd-soc-sunxi-dsd-objs := sunxi-dsd.o
snd-soc-sunxi-dmic-objs := sunxi-dmic.o
snd-soc-sunxi-rwfunc-objs := sunxi_rw_func.o
snd-soc-sunxi-inter-i2s-objs := sunxi-inter-i2s.o

obj-$(CONFIG_SND_SUNXI_SOC) += snd-soc-sunxi.o
obj-$(CONFIG_SND_SUNXI_SOC_HDMI) += snd-soc-sunxi-hdmi.o
obj-$(CONFIG_SND_SUNXI_SOC_DAUDIO) += snd-soc-sunxi-daudio.o
obj-$(CONFIG_SND_SUNXI_SOC_SPDIF) += snd-soc-sunxi-spdif.o
obj-$(CONFIG_SND_SUNXI_SOC_CPUDAI) += snd-soc-sunxi-cpudai.o
obj-$(CONFIG_SND_SUNXI_SOC_DSD) += snd-soc-sunxi-dsd.o
obj-$(CONFIG_SND_SUNXI_SOC_DMIC) += snd-soc-sunxi-dmic.o
obj-$(CONFIG_SND_SUNXI_SOC_RWFUNC) += snd-soc-sunxi-rwfunc.o
obj-$(CONFIG_SND_SUNXI_SOC_INTER_I2S) += snd-soc-sunxi-inter-i2s.o

# SUNXI Codec Embedded Support
obj-$(CONFIG_SND_SUN8IW7_CODEC) += sun8iw7-codec.o
obj-$(CONFIG_SND_SUN8IW11_CODEC) += sun8iw11-codec.o
obj-$(CONFIG_SND_SUN8IW12_CODEC) += sun8iw12-codec.o


# SUNXI Machine Support
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW7_CODEC) += sun8iw7-sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW11_CODEC) += sun8iw11-sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW12_CODEC) += sun8iw12-sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_SUNXI_HDMIAUDIO) += sunxi-sndhdmi.o
obj-$(CONFIG_SND_SUNXI_SOC_SUNXI_DAUDIO) += sunxi-snddaudio.o
obj-$(CONFIG_SND_SUNXI_SOC_SUNXI_SPDIF) += sunxi-sndspdif.o
obj-$(CONFIG_SND_SUNXI_SOC_SUNXI_DSD) += sunxi-snddsd.o
obj-$(CONFIG_SND_SUNXI_SOC_SUNXI_DMIC) += sunxi-snddmic.o

