# Makefile for the Linux video drivers on sunxi platform.
# 30 Sep 2016, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_DISP2_SUNXI) += disp2/disp/

obj-$(CONFIG_HDMI_DISP2_SUNXI) += disp2/hdmi/

obj-$(CONFIG_TV_DISP2_SUNXI) += disp2/tv/

obj-$(CONFIG_DISP2_TV_AC200) += disp2/tv/
